-- Online Chess / Supabase schema
-- Run this entire file in Supabase Dashboard -> SQL Editor.
-- Then enable Anonymous Sign-Ins in Authentication -> Providers / Sign In options.

create extension if not exists pgcrypto;

create table if not exists public.games (
  id uuid primary key default gen_random_uuid(),
  white_player_id uuid not null references auth.users(id) on delete cascade,
  black_player_id uuid references auth.users(id) on delete set null,
  fen text not null,
  pgn text not null default '',
  turn text not null default 'white' check (turn in ('white', 'black')),
  status text not null default 'waiting' check (status in ('waiting', 'active', 'checkmate', 'draw', 'resigned')),
  winner_id uuid references auth.users(id) on delete set null,
  draw_reason text,
  last_move text,
  last_move_san text,
  version integer not null default 0 check (version >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint different_players check (black_player_id is null or black_player_id <> white_player_id)
);

create table if not exists public.moves (
  id bigint generated by default as identity primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  player_id uuid not null references auth.users(id) on delete cascade,
  ply_number integer not null check (ply_number > 0),
  color text not null check (color in ('white', 'black')),
  from_square text not null check (from_square ~ '^[a-h][1-8]$'),
  to_square text not null check (to_square ~ '^[a-h][1-8]$'),
  promotion text check (promotion is null or promotion in ('q', 'r', 'b', 'n')),
  san text not null,
  fen_after text not null,
  created_at timestamptz not null default now(),
  unique (game_id, ply_number)
);

create index if not exists games_white_player_idx on public.games(white_player_id);
create index if not exists games_black_player_idx on public.games(black_player_id);
create index if not exists moves_game_idx on public.moves(game_id, ply_number);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists games_set_updated_at on public.games;
create trigger games_set_updated_at
before update on public.games
for each row execute function public.set_updated_at();

alter table public.games enable row level security;
alter table public.moves enable row level security;

-- Browsers may only READ games they participate in.
-- All inserts/updates are performed by protected Next.js API routes using a server secret key.
drop policy if exists "players can read their games" on public.games;
create policy "players can read their games"
on public.games
for select
to authenticated
using (auth.uid() = white_player_id or auth.uid() = black_player_id);

-- Players may read the move log only for games they belong to.
drop policy if exists "players can read moves in their games" on public.moves;
create policy "players can read moves in their games"
on public.moves
for select
to authenticated
using (
  exists (
    select 1
    from public.games g
    where g.id = moves.game_id
      and (g.white_player_id = auth.uid() or g.black_player_id = auth.uid())
  )
);

-- Enable Realtime Postgres Changes for the game row.
-- Idempotent: only adds the table if it is not already in the publication.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'games'
  ) then
    alter publication supabase_realtime add table public.games;
  end if;
end
$$;

-- Explicit grants for projects created with "Automatically expose new tables" disabled.
grant usage on schema public to authenticated;
grant select on table public.games to authenticated;
grant select on table public.moves to authenticated;

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.games to service_role;
grant select, insert, update, delete on table public.moves to service_role;
grant usage, select on all sequences in schema public to service_role;
